python3 train_dalle.py \
--text_seq_len 225 --batch_size 5 --epochs 10 \
--learning_rate 0.0006  --lr_decay \
--depth 8  \
--image_text_folder ~/datasets/ \
--data_file ~/datasets/mannequin_multi/pose_multi_train.pickle \
--test_data_file ~/datasets/mannequin_multi/pose_multi_test.pickle \
--data_type pose \
--pose_format keypoint \
--pose_seq_len 25 \
--pose_dim 9 \
--wandb_name dalle_mannequin_pose_final \
--taming \
--vqgan_config_path ../VQGAN-CLIP/checkpoints/vqgan_mannequin.yaml \
--vqgan_model_path ../VQGAN-CLIP/checkpoints/vqgan_mannequin.ckpt \
--cuda cuda:1  \
--hug --bpe_path /home/soon/github/PoseGuidedTextToImage/tokenizer-mannequin.json \
--dalle_output_file_name checkpoint/final/sdalle_mannequin_pose_kp \
--display_freq 50