python3 train_dalle.py \
--text_seq_len 128 --batch_size 8 --epochs 100 \
--learning_rate 0.0006  --lr_decay \
--depth 12  \
--image_text_folder ~/datasets/deepfashion/In-shop/ \
--data_file ~/github/PoseGuidedTextToImage/dataset/pose_openpose_deepfashion_inshop_train.pickle \
--test_data_file ~/github/PoseGuidedTextToImage/dataset/pose_openpose_deepfashion_inshop_test.pickle \
--data_type pose \
--pose_format image \
--pose_seq_len 256 \
--pose_dim 3 \
--pose_image_downscale 4 \
--wandb_name dalle_deepfashion_final \
--taming \
--vqgan_config_path ../VQGAN-CLIP/checkpoints/deepfashion.yaml \
--vqgan_model_path ../VQGAN-CLIP/checkpoints/deepfashion_1225_45.ckpt \
--cuda cuda:2  \
--hug --bpe_path /home/soon/github/PoseGuidedTextToImage/tokenizer-mannequin.json \
--dalle_output_file_name checkpoints/final/dalle_deepfashion_image_64 \
--display_freq 200 
#--dalle_path dalle_mannequin_pose_keypoint_aug.pt
